spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nissar-ahmad/config-repo
          clone-on-start: true
          default-label: main
server:
  port: 8888
